import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@/css/satoshi.css';
import '@/css/style.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SDN 2 Tamanharjo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className + ' min-h-screen antialiased'}>{children}
      </body>
    </html>
  );
}

